# Generated by Django 2.1 on 2018-10-05 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default='2006-10-25 14:30:59')),
                ('message', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Post')),
            ],
        ),
    ]
