# Generated by Django 2.1 on 2018-10-17 08:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=ckeditor.fields.RichTextField(max_length=256),
        ),
    ]
