# Generated by Django 2.1 on 2018-09-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default='2006-10-25 14:30:59'),
        ),
    ]
