# Generated by Django 2.1 on 2018-09-02 11:15

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180902_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to=apps.events.models.get_image_path),
        ),
    ]
