# Generated by Django 2.1 on 2018-10-15 10:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181005_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='lan',
            field=models.DecimalField(blank=True, decimal_places=145, max_digits=150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=145, max_digits=150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
