# Generated by Django 2.1 on 2018-10-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationdetails',
            old_name='name',
            new_name='display_name',
        ),
    ]
