# Generated by Django 2.1 on 2018-08-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
