# Generated by Django 2.1 on 2018-08-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
