# Generated by Django 2.1 on 2018-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='isClose',
            field=models.BooleanField(default=False),
        ),
    ]
