# Generated by Django 2.1 on 2018-10-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpreferences',
            name='user',
        ),
        migrations.DeleteModel(
            name='FoodPreferences',
        ),
    ]
