# Generated by Django 2.1 on 2018-09-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_optioninsurvey_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyparticipation',
            old_name='event',
            new_name='survey',
        ),
    ]
