# Generated by Django 2.1 on 2018-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20181002_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='isFinalized',
            field=models.BooleanField(default=False),
        ),
    ]
