# Generated by Django 2.1 on 2018-10-05 01:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_isfinalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioninsurvey',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='optioninsurvey',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
