# Generated by Django 2.1 on 2018-09-13 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20180913_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyparticipation',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
    ]
