# Generated by Django 2.1 on 2018-09-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20180913_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoose',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.InvolvedEvent'),
        ),
    ]
