# Generated by Django 2.1 on 2018-10-05 02:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20181005_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioninsurvey',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
    ]
